### ISSUE TITLE
ModuleNotFoundError: No module named 'keyring.util.escape'

### ISSUE THREAD

**Issue by HeloiseS** [fpavogt/fcmaker#14]
Hi, 

I'm trying to import fcmaker in python 3.6.8, I have made sure to install keyring, but it seems that fcmaker uses a function that no longer exists in this version  (I tried keyring.__version__ but apparent;y the module does nto have a version attribute - weird). 

Given what I get from `help(keyring.util)`, it does not look like keyring.util.escape exists:
```
Help on package keyring.util in keyring:

NAME
    keyring.util

PACKAGE CONTENTS
    platform_
    properties

FUNCTIONS
    once(func)
        Decorate func so it's only ever called the first time.
        
        This decorator can ensure that an expensive or non-idempotent function
        will not be expensive on subsequent calls and is idempotent.
        
        >>> func = once(lambda a: a+3)
        >>> func(3)
        6
        >>> func(9)
        6
        >>> func('12')
        6
    
    suppress_exceptions(callables, exceptions=<class 'Exception'>)
        yield the results of calling each element of callables, suppressing
        any indicated exceptions.

FILE
    /home/fste075/.local/lib/python3.6/site-packages/keyring/util/__init__.py
```

Cheers,
Heloise

**Comment by fpavogt** [comment]
Hi, 

I was using keyring 18.0.0, and had no issue. I just upgraded to the latest version (19.1.0), but still cannot reproduce the issue. What error message do you get when you try to import fcmaker ? 

You should be able to get the version of keyring with a "pip list".

**Comment by HeloiseS** [comment]
hi,

Thanks for the prompt reply. I've got keyring 19.1.0 and this is the error I get when I try to import fcmaker:

```
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/fste075/.local/lib/python3.6/site-packages/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/fste075/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/fste075/.local/lib/python3.6/site-packages/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/fste075/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/fste075/.local/lib/python3.6/site-packages/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/fste075/.local/lib/python3.6/site-packages/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Created TAP+ (v1.0.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: False
	Port: 80
	SSL Port: 443
```

Cheers,
H

**Comment by fpavogt** [comment]
Interesting ... 
First thing is that fcmaker does not use keyring directly. And so I suspect that this error happens when fcmaker imports astroquery. Could you try the following imports manually, to see if you get the same messages ?

`from astroquery.skyview import SkyView`
`from astroquery.vizier import Vizier`
`from astroquery.gaia import Gaia`

If you do, then it would be best to post the issue to the [astroquery Github repo](https://github.com/astropy/astroquery/issues?utf8=%E2%9C%93&q=is%3Aissue+keyring). Looking around the web for similar error reports, I also found a few like [this one](https://github.com/jrnl-org/jrnl/issues/558), where the possible fix is: `pip3 install --upgrade keyring.alt`

And one last question: are you running Windows ?

**Comment by HeloiseS** [comment]
Hi, 

The Skyview import does fail on keyring - the other two are good. I'll try to poke the astroquery people, thanks for the prompt response. 

And no I am not on windows - Ubuntu 18.04
:)

**Comment by HeloiseS** [comment]
Quick update.... I fixed it, but I'm not sure how that happened - here is what I gathered:

- keyring import was fine, the failure happened at the module level where the 'keyring.util.escape' module could not be found. 
- As you can see in my comment from [a few days ago just above](https://github.com/fpavogt/fcmaker/issues/14#issue-488326651 ), 'escape' did NOT exist in 'keyring.util'
- I googled that and saw people saying that the path no longer existed on newer versions of keyring. So I attenpted to download 13.2.0, but that would fail to import for another reason. I tried a more recent version: 15.0.0. That failed to import too.... Then I reverted back to the most recent version (19.1.0) in order to start from square one. 
- I then imported `astroquery.skyview.SkyView` just to recreate the error message... and it worked?
- I checked the help of the util package and loe and behold:
```
NAME
    keyring.util

PACKAGE CONTENTS
    **escape**
    platform_
    properties

FUNCTIONS
    once(func)
        Decorate func so it's only ever called the first time.
        
        This decorator can ensure that an expensive or non-idempotent function
        will not be expensive on subsequent calls and is idempotent.
        
        >>> func = once(lambda a: a+3)
        >>> func(3)
        6
        >>> func(9)
        6
        >>> func('12')
        6
    
    suppress_exceptions(callables, exceptions=<class 'Exception'>)
        yield the results of calling each element of callables, suppressing
        any indicated exceptions.

FILE
    /home/fste075/.local/lib/python3.6/site-packages/keyring/util/__init__.py
```

... `keyring.util.escape` now exists.

I don't know what happened. I did try to uninstall and re-install 3 days ago to no avail. 

*magic*

**Comment by fpavogt** [comment]
Magic it is! Glad you got it working in the end. 

Cheers, 
Frédéric
