### ISSUE TITLE
Demo crashes - 

### ISSUE THREAD

**Issue by HeloiseS** [fpavogt/fcmaker#17]

**Comment by HeloiseS** [comment]
Hi,

The demo crashes with FORS2 as well (I don't think this OB is filled up to be honest - still thought I'd report it). 



```
>>> python -m fcmaker --demo

WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Created TAP+ (v1.0.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: False
	Port: 80
	SSL Port: 443
OB Id from p2: 1985485
 
1985485: fetching the OB parameters ...
   I found an ephemeris file, and stored it: ././fcm_data/ephem_1985485.txt
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/__main__.py", line 214, in <module>
    do_parang = args.do_parang,
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 249, in make_fc
    fc_params = fcm_id.get_p2fcdata(obID, api)
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/fcmaker_instrument_dispatch.py", line 553, in get_p2fcdata
    fc_params = get_target_from_ephem(fc_params, ephemeris)
  File "/home/fste075/.local/lib/python3.6/site-packages/fcmaker/fcmaker_instrument_dispatch.py", line 405, in get_target_from_ephem
    if (fcm_m.obsdate>times[-1]) or (fcm_m.obsdate<times[0]):
IndexError: list index out of range
```

**Comment by fpavogt** [comment]
Hi, 

FORS is not supported by fcmaker. From what I can tell, this error arise because the ephemeris file is not having the proper structure. I suppose that the code should be able to spit a clearer error if that happens. I'll put this on the to-do list.

**Comment by HeloiseS** [comment]
I fixed it on my system by simply moving the instrument check code block up - I made a pull request so you can merge and try it out. There is no reason it should break anything else but with code, who knows?

:)

**Comment by fpavogt** [comment]
Fixed in [v105,](https://github.com/fpavogt/fcmaker/tree/v105.0.0). Thanks for reporting it!
