### ISSUE TITLE
fcmaker: ImportError: cannot import name '_get_download_cache_locs'

### ISSUE THREAD

**Issue by gallc1** [fpavogt/fcmaker#18]
Hi,
I've installed fcmaker into a conda environment (called test_env36) and the installation worked fine. But when funning fcmaker, e.g., just testing it with 'python -m fcmaker --help' I am getting following error, but I don't know what the problem is or how to fix this. Any help is much appreciated! 

(test_env36) bash-3.2$ python -m fcmaker --help
Traceback (most recent call last):
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/site-packages/fcmaker/__init__.py", line 29, in <module>
    from .fcmaker import * # So that users only need to do import fcmaker
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 14, in <module>
    from . import fcmaker_instrument_dispatch as fcm_id
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/site-packages/fcmaker/fcmaker_instrument_dispatch.py", line 21, in <module>
    from . import fcmaker_xshooter as fcm_xshooter
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/site-packages/fcmaker/fcmaker_xshooter.py", line 8, in <module>
    from astroplan import Observer
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/site-packages/astroplan/__init__.py", line 23, in <module>
    from .utils import *
  File "/Users/christagall/anaconda2/envs/test_env36/lib/python3.6/site-packages/astroplan/utils.py", line 15, in <module>
    from astropy.utils.data import _get_download_cache_locs, CacheMissingWarning
ImportError: cannot import name '_get_download_cache_locs'

**Comment by fpavogt** [comment]
Hi @gallc1. Thanks for the bug report. 

Note that I am not maintaining fcmaker any more. Having said that, let's see if we can figure this one out. 

From the error message, it looks like the bug comes from the astroplan package. I just tried to do the same as you, but I cannot reproduce it. 

I am also using a conda environment, with the following specs:
  - python 3.8.3
  - astroplan  0.7
  - astropy  4.0.1.post1
  - astroquery  0.4.1
  - fcmaker 105.0.0

From your error message, it looks like you may be using Python 3.6 ? Could you try upgrading to 3.8, and match the same package version as listed here, and then try again ? 

Also what operating system are you using ?

**Comment by gallc1** [comment]
I created a new environment with python 3.8 now and it worked. Thank you so much for your help!

**Comment by fpavogt** [comment]
No worries !
