### ISSUE TITLE
 urllib.error.URLError: SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by fpavogt** [fpavogt/fcmaker#2]
One user reports the following: 

```
>> python3 -m fcmaker 
.....

   Downloading the DSS2 Red background image with SkyView ...

WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
Traceback (most recent call last):

File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open

    encode_chunked=req.has_header('Transfer-encoding'))

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output

    self.send(msg)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send

    self.connect()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect

    server_hostname=server_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket

    _context=self, _session=session)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__

    self.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake

    self._sslobj.do_handshake()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/__main__.py", line 210, in <module>

    do_parang = args.do_parang,

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 240, in make_fc

    do_pdf=do_pdf, do_png=do_png)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/fcmaker_plots.py", line 344, in draw_fc

    (fn_bk_image_R, survey_R, bk_lam_R) = get_bk_image('DSS2 Red', None, right_center, right_radius, fc_params)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/fcmaker_plots.py", line 171, in get_bk_image

    pixels='%i' %((fcm_m.bk_radius/fcm_m.bk_pix).to(u.arcsec/u.arcsec).value),

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroquery/skyview/core.py", line 207, in get_images

    return [obj.get_fits() for obj in readable_objects]

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroquery/skyview/core.py", line 207, in <listcomp>

    return [obj.get_fits() for obj in readable_objects]

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroquery/utils/commons.py", line 355, in get_fits

    filedata = self.get_string()

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroquery/utils/commons.py", line 419, in get_string

    raise e

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroquery/utils/commons.py", line 411, in get_string

    with self._readable_object as f:

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__

    return next(self.gen)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/utils/data.py", line 192, in get_readable_fileobj

    timeout=remote_timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/utils/data.py", line 1088, in download_file

    raise e

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astropy/utils/data.py", line 1021, in download_file

    with urllib.request.urlopen(remote_url, timeout=timeout) as remote:

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen

    return opener.open(url, data, timeout)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open

    response = self._open(req, data)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open

    '_open', req)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain

    result = func(*args)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open

    context=self._context, check_hostname=self._check_hostname)

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open

    raise URLError(err)

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)>
```

**Comment by fpavogt** [comment]
This is most likely not related to fcmaker directly, but it would still be good to find the root cause behind. Is there some package missing from the pip required list ?

**Comment by fpavogt** [comment]
After some digging with the user, we found (many) StackOverflow et al. entries about this issue related to the ``certifi`` package on Mac OSX and a "default" installation (i.e. not Anaconda). 
See e.g. [this link](https://bugs.python.org/issue28150).

The user fixed the problem by a) running the script described on this [StackOverflow post](https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate), and b) clearing the SkyView cache by running fcmaker with the ``--clear-SkyView-cache`` once.
