### ISSUE TITLE
get_p2fcdata_hawki() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by fpavogt** [fpavogt/fcmaker#3]
One user reports the following error, for a HAWKI OB on p2:

2059158: fetching the OB parameters ...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/__main__.py", line 210, in <module>
    do_parang = args.do_parang,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 234, in make_fc
    fc_params = fcm_id.get_p2fcdata(obID, api)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fcmaker/fcmaker_instrument_dispatch.py", line 518, in get_p2fcdata
    return fcm_hawki.get_p2fcdata_hawki(fc_params, ob, api)
TypeError: get_p2fcdata_hawki() takes 2 positional arguments but 3 were given

**Comment by fpavogt** [comment]
The functions ``get_p2fcdata_hawki`` and ``get_p2fcdata_hawki`` are missing the ``fc_params`` dictionary as a first argument for some strange reason. Will be fixed in v0.3.6.
