### ISSUE TITLE
Invalid time input

### ISSUE THREAD

**Issue by mheida** [fpavogt/fcmaker#6]
Hi Frederic,

First of all, thanks for making this tool available! I'm running into an issue that may very well be due to something in my OB but I can't figure out what's wrong. After the message 'fetching the OB parameters...' I get the error pasted below. It seems to be looking for a time somewhere but there shouldn't be one in my OB - it's not a time-critical observation. I tried including a given PA instead of parallactic but that doesn't make a difference. Can you tell me what I might be doing wrong?

Thanks!
Marianne

Traceback (most recent call last):
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/coordinates/attributes.py", line 182, in convert_input
    out = Time(value)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/time/core.py", line 280, in __init__
    precision, in_subfmt, out_subfmt)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/time/core.py", line 330, in _init_from_vals
    precision, in_subfmt, out_subfmt)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/time/core.py", line 374, in _get_time_fmt
    raise ValueError('Input values did not match {0}'.format(err_msg))
ValueError: Input values did not match any of the formats where the format keyword is optional ['datetime', 'iso', 'isot', 'yday', 'fits', 'byear_str', 'jyear_str']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/fcmaker/__main__.py", line 210, in <module>
    do_parang = args.do_parang,
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 234, in make_fc
    fc_params = fcm_id.get_p2fcdata(obID, api)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/fcmaker/fcmaker_instrument_dispatch.py", line 494, in get_p2fcdata
    distance=100*u.pc,  
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py", line 238, in __init__
    setattr(self, attr, kwargs[attr])
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/coordinates/sky_coordinate.py", line 716, in __setattr__
    frame_transform_graph.frame_attributes[attr].__get__(self)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/coordinates/attributes.py", line 105, in __get__
    out, converted = self.convert_input(out)
  File "/Users/mheida/software/miniconda2/envs/envpy3/lib/python3.6/site-packages/astropy/coordinates/attributes.py", line 186, in convert_input
    value, err))
ValueError: Invalid time input equinox='2000.00'
Input values did not match any of the formats where the format keyword is optional ['datetime', 'iso', 'isot', 'yday', 'fits', 'byear_str', 'jyear_str']

**Comment by fpavogt** [comment]
Dear Marianne, 

Under the "target" tab in p2, the "equinox" value should be "J2000". Can you check if this is the case, and if not, try to run the code again with this ? 

Out of curiosity, did you import the target from the Phase 1 using the button in p2 ? It seems that when doing that, the default "J2000" value of the equinox present one you first creates an OB is replaced by "2000" only, which fcmaker doesn't like. 

I will patch fcmaker in the next release. But I think this is a p2 bug to start with. Would you mind submitting a bug report to usd-help@eso.org, to make the p2 crew aware of this ? 

Thanks for reporting this!
Frédéric

**Comment by mheida** [comment]
Dear Frédéric,

You're right, that solved the issue. And yes, that equinox value came from the import target button. I'll send an email to ESO.

Thanks!
Marianne

**Comment by fpavogt** [comment]
Excellent. Will leave this open until I have implemented a safety check in fcmaker. If you ever get a ETA for the p2 fix from ESO, fon't hesitate to add the info here. No doubt others will experience the same issue until then.

**Comment by fpavogt** [comment]
Implemented in v0.3.8.
