### ISSUE TITLE
HTTPError

### ISSUE THREAD

**Issue by astrom-tom** [fpavogt/fcmaker#8]
Dear Frederic,

We found a strange error on fcmaker that deals with the HTTP package. The full printout of fxmaker shows (see at the bottom for the traceback of the error)

2143401: fetching the OB parameters ...
2143401: creating the finding chart ...
   Downloading the SDSSr background image with SkyView ...
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
Downloading https://skyview.gsfc.nasa.gov/tempspace/fits/skv703270614345.fits
|==========================================|  16M/ 16M (100.00%)      1m13s
   Downloading the DSS2 Red background image with SkyView ...
WARNING: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError. [astropy.units.quantity]
INFO: Auto-setting vmin to -5.850e-02 [aplpy.core]
INFO: Auto-setting vmax to  2.129e-01 [aplpy.core]
INFO: Auto-setting vmin to  5.233e+03 [aplpy.core]
INFO: Auto-setting vmax to  1.066e+04 [aplpy.core]
   Querying GAIA DR2 to look for high proper motion stars in the area ...
Traceback (most recent call last):
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/site-packages/fcmaker/__main__.py", line 210, in <module>
    do_parang = args.do_parang,
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/site-packages/fcmaker/fcmaker.py", line 240, in make_fc
    do_pdf=do_pdf, do_png=do_png)
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/site-packages/fcmaker/fcmaker_plots.py", line 401, in draw_fc
    j = Gaia.cone_search(left_center, right_radius*u.arcsec, verbose=False)
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/gaia/core.py", line 408, in cone_search
    dump_to_file=dump_to_file)
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/gaia/core.py", line 373, in __cone_search
    dump_to_file=dump_to_file)
  File "/Users/blabla/anaconda3/envs/py36/lib/python3.6/site-packages/astroquery/utils/tap/core.py", line 241, in launch_job
    raise requests.exceptions.HTTPError(response.reason)
requests.exceptions.HTTPError: Service Unavailable

As far as we see the file gets downloaded as it can be opened in ds9.

Cheers,

R.

**Comment by fpavogt** [comment]
A few people have reported this. I think this occurs when one download gets interrupted, which corrupts something in the skyview cache. Then if you try again, the download may succeed, but it would still crash down the line for reasons I don't understand. 

Can you try to run the exact same command, but with the `--clear-SkyView-cache` flag ?
Can you confirm other OBs run fine ?
